name: Automerge

on:
  pull_request:
    branches: [ 'master', 'stable-*', 'feature/*' ]

jobs:
  automerge:
    #if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      # All other permissions are set to none
      checks: write
      contents: read
      pull-requests: write
    steps:

    - name: "Checkout ansible-hub-ui (${{ github.ref }})"
      uses: actions/checkout@v3

    - name: "Install node 16"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: "Echo variables"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ github.event.pull_request.url }}"
        echo "${{ github.event.pull_request.number }}"
        gh pr merge ${{ github.event.pull_request.number }} -s --admin
    
    - name: "Run automerge.js"
      working-directory: ".github/workflows"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        node automerge.js "${{ github.head_ref }}" "${{ github.event.pull_request.title }}" "${{ github.actor }}"

    - name: "Automerge the PR"
      working-directory: ".github/workflows"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Automerge of PR"
        gh pr merge "${{ github.event.pull_request.url }}"
